// <auto-generated />
namespace database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class loginifno : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(loginifno));
        
        string IMigrationMetadata.Id
        {
            get { return "202102031111014_loginifno"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
