// <auto-generated />
namespace webapp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class loginifno : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(loginifno));
        
        string IMigrationMetadata.Id
        {
            get { return "202102031108009_loginifno"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
